In [225]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time 
import datetime

# Data Processing

## Loading data

In [2]:
df_hospital_org = pd.read_csv('/Users/jessie/Desktop/summer_project/Definitive_Healthcare%3A_USA_Hospital_Beds.csv', usecols = ['COUNTY_NAME', 'STATE_NAME', 'NUM_LICENSED_BEDS', 'NUM_STAFFED_BEDS', 'AVG_VENTILATOR_USAGE'])
df_social_mobility_org = pd.read_csv('/Users/jessie/Desktop/summer_project/social_mobility_data(up_to_date)/County.csv', usecols = ['CTNAME', 'STFIPS', 'date', 'Social distancing index', 'New cases/1000 people', 'Population density', '% people older than 60', 'COVID death rate'])
df_COVID19_org = pd.read_csv('/Users/jessie/Documents/GitHub/COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv')
df_state_fips = pd.read_csv('/Users/jessie/Desktop/summer_project/social_mobility_data(up_to_date)/fips-states.csv', usecols = ['state_name', 'fips'])

In [3]:
print(df_hospital_org.shape)
df_hospital_org.head()

(6622, 5)

,COUNTY_NAME,STATE_NAME,NUM_LICENSED_BEDS,NUM_STAFFED_BEDS,AVG_VENTILATOR_USAGE
0,Maricopa,Arizona,62.0,62.0,0.0
1,Pima,Arizona,295.0,295.0,2.0
2,Fresno,California,54.0,54.0,2.0
3,New Haven,Connecticut,216.0,216.0,2.0
4,New Castle,Delaware,62.0,62.0,1.0

In [4]:
print(df_social_mobility_org.shape)
df_social_mobility_org.head()

(559276, 8)

,CTNAME,STFIPS,Social distancing index,date,% people older than 60,Population density,COVID death rate,New cases/1000 people
0,Autauga County,1,54,01/01/2020,19,91,0.0,0.0
1,Autauga County,1,25,01/02/2020,19,91,0.0,0.0
2,Autauga County,1,15,01/03/2020,19,91,0.0,0.0
3,Autauga County,1,33,01/04/2020,19,91,0.0,0.0
4,Autauga County,1,40,01/05/2020,19,91,0.0,0.0

In [5]:
print(df_COVID19_org.shape)
df_COVID19_org.head()

(3261, 177)

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,...,6/26/20,6/27/20,6/28/20,6/29/20,6/30/20,7/1/20,7/2/20,7/3/20,7/4/20,7/5/20
0,16,AS,ASM,16,60.0,NaN,American Samoa,US,-14.2710,-170.1320,...,0,0,0,0,0,0,0,0,0,0
1,316,GU,GUM,316,66.0,NaN,Guam,US,13.4443,144.7937,...,247,247,247,253,257,267,280,280,280,280
2,580,MP,MNP,580,69.0,NaN,Northern Mariana Islands,US,15.0979,145.6739,...,30,30,30,30,30,30,31,31,31,31
3,630,PR,PRI,630,72.0,NaN,Puerto Rico,US,18.2208,-66.5901,...,6922,7066,7189,7250,7465,7537,7608,7683,7787,7916
4,850,VI,VIR,850,78.0,NaN,Virgin Islands,US,18.3358,-64.8963,...,81,81,81,81,81,90,92,98,111,111

In [6]:
print(df_state_fips.shape)
df_state_fips.head()

(51, 2)

   state_name  fips
0     Alabama     1
1      Alaska     2
2     Arizona     4
3    Arkansas     5
4  California     6

## Preprocess Hospital resources data

In [7]:
print(df_hospital_org.isnull().sum())
df_hospital = df_hospital_org.dropna()

COUNTY_NAME              28
STATE_NAME               28
NUM_LICENSED_BEDS       150
NUM_STAFFED_BEDS        238
AVG_VENTILATOR_USAGE     71
dtype: int64

In [8]:
print(df_hospital.dtypes)
print(df_hospital.describe())

df_hospital['COUNTY'] = df_hospital['COUNTY_NAME'] + str(',') + df_hospital["STATE_NAME"]
df_hospital_group = df_hospital.groupby(by = 'COUNTY').agg('sum').reset_index()

df_hospital_group.drop(df_hospital_group.loc[(df_hospital_group['NUM_STAFFED_BEDS']/ df_hospital_group['NUM_LICENSED_BEDS'] <= 0.1) 
                                             & (df_hospital_group['NUM_STAFFED_BEDS'] <= 10)].index, inplace = True)
print(len(df_hospital_group))
df_hospital_group.head()

COUNTY_NAME              object
STATE_NAME               object
NUM_LICENSED_BEDS       float64
NUM_STAFFED_BEDS        float64
AVG_VENTILATOR_USAGE    float64
dtype: object
       NUM_LICENSED_BEDS  NUM_STAFFED_BEDS  AVG_VENTILATOR_USAGE
count        6356.000000       6356.000000           6356.000000
mean          150.487256        128.924638              3.650409
std           183.131072        160.582287              5.517830
min             1.000000          1.000000              0.000000
25%            26.000000         25.000000              0.000000
50%            79.000000         66.000000              2.000000
75%           200.000000        168.000000              4.000000
max          2059.000000       2753.000000             61.000000
2491

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

,COUNTY,NUM_LICENSED_BEDS,NUM_STAFFED_BEDS,AVG_VENTILATOR_USAGE
0,"Abbeville,South Carolina",25.0,25.0,2.0
1,"Acadia,Louisiana",170.0,144.0,3.0
2,"Accomack,Virginia",52.0,46.0,3.0
3,"Ada,Idaho",1311.0,1240.0,24.0
4,"Adair,Iowa",25.0,25.0,0.0

## Preprocess social mobility data

In [373]:
print(df_social_mobility_org.isnull().sum())
df_social_mobility = df_social_mobility_org.dropna()

CTNAME                     0
STFIPS                     0
Social distancing index    0
date                       0
% people older than 60     0
Population density         0
COVID death rate           0
New cases/1000 people      0
dtype: int64

In [374]:
df_social_mobility['CTNAME'] = df_social_mobility['CTNAME'].apply(lambda x: x.replace(str(' County'), ''))
df_social_mobility_merge = pd.merge(df_social_mobility, df_state_fips, left_on = 'STFIPS', right_on = 'fips')
df_social_mobility_merge['COUNTY'] = df_social_mobility_merge['CTNAME'] + str(',') + df_social_mobility_merge['state_name']
df_social_mobility_merge.drop(columns = ['CTNAME', 'STFIPS', 'state_name', 'fips'], inplace = True)
df_social_mobility_merge.head()
#df_social_mobility_group = df_social_mobility_merge.groupby(by = 'date')

#print(df_social_mobility_group.size())
#df_social_mobility_current = df_social_mobility_group.get_group('06/22/2020')

# print(df_social_mobility_current.dtypes)
# print(df_social_mobility_current.describe())
# df_social_mobility_current.head()
#df_social_mobility_current['Population density'].plot.hist()

#df_social_mobility_current.loc[df_social_mobility_current['Population density'] == 0]
#len(df_social_mobility_group.get_group('01/01/2020')['COUNTY'].unique())

,Social distancing index,date,% people older than 60,Population density,COVID death rate,New cases/1000 people,COUNTY
0,54,01/01/2020,19,91,0.0,0.0,"Autauga,Alabama"
1,25,01/02/2020,19,91,0.0,0.0,"Autauga,Alabama"
2,15,01/03/2020,19,91,0.0,0.0,"Autauga,Alabama"
3,33,01/04/2020,19,91,0.0,0.0,"Autauga,Alabama"
4,40,01/05/2020,19,91,0.0,0.0,"Autauga,Alabama"

## Preprocess COVID19 data

In [13]:
print(df_COVID19_org.isnull().sum())
df_COVID19 = df_COVID19_org.dropna()
print(df_COVID19.shape)

UID                0
iso2               0
iso3               0
code3              0
FIPS              10
Admin2             7
Province_State     0
Country_Region     0
Lat                0
Long_              0
Combined_Key       0
1/22/20            0
1/23/20            0
1/24/20            0
1/25/20            0
1/26/20            0
1/27/20            0
1/28/20            0
1/29/20            0
1/30/20            0
1/31/20            0
2/1/20             0
2/2/20             0
2/3/20             0
2/4/20             0
2/5/20             0
2/6/20             0
2/7/20             0
2/8/20             0
2/9/20             0
                  ..
6/6/20             0
6/7/20             0
6/8/20             0
6/9/20             0
6/10/20            0
6/11/20            0
6/12/20            0
6/13/20            0
6/14/20            0
6/15/20            0
6/16/20            0
6/17/20            0
6/18/20            0
6/19/20            0
6/20/20            0
6/21/20            0
6/22/20            0
6/23/20            0
6/24/20            0
6/25/20            0
6/26/20            0
6/27/20            0
6/28/20            0
6/29/20            0
6/30/20            0
7/1/20             0
7/2/20             0
7/3/20             0
7/4/20             0
7/5/20             0
Length: 177, dtype: int64
(3244, 177)

In [14]:
df_COVID19.columns.to_series()

UID                          UID
iso2                        iso2
iso3                        iso3
code3                      code3
FIPS                        FIPS
Admin2                    Admin2
Province_State    Province_State
Country_Region    Country_Region
Lat                          Lat
Long_                      Long_
Combined_Key        Combined_Key
1/22/20                  1/22/20
1/23/20                  1/23/20
1/24/20                  1/24/20
1/25/20                  1/25/20
1/26/20                  1/26/20
1/27/20                  1/27/20
1/28/20                  1/28/20
1/29/20                  1/29/20
1/30/20                  1/30/20
1/31/20                  1/31/20
2/1/20                    2/1/20
2/2/20                    2/2/20
2/3/20                    2/3/20
2/4/20                    2/4/20
2/5/20                    2/5/20
2/6/20                    2/6/20
2/7/20                    2/7/20
2/8/20                    2/8/20
2/9/20                    2/9/20
                       ...
6/6/20                    6/6/20
6/7/20                    6/7/20
6/8/20                    6/8/20
6/9/20                    6/9/20
6/10/20                  6/10/20
6/11/20                  6/11/20
6/12/20                  6/12/20
6/13/20                  6/13/20
6/14/20                  6/14/20
6/15/20                  6/15/20
6/16/20                  6/16/20
6/17/20                  6/17/20
6/18/20                  6/18/20
6/19/20                  6/19/20
6/20/20                  6/20/20
6/21/20                  6/21/20
6/22/20                  6/22/20
6/23/20                  6/23/20
6/24/20                  6/24/20
6/25/20                  6/25/20
6/26/20                  6/26/20
6/27/20                  6/27/20
6/28/20                  6/28/20
6/29/20                  6/29/20
6/30/20                  6/30/20
7/1/20                    7/1/20
7/2/20                    7/2/20
7/3/20                    7/3/20
7/4/20                    7/4/20
7/5/20                    7/5/20
Length: 177, dtype: object

In [16]:
df_COVID19_demo = df_COVID19[['Admin2', 'Province_State', 'Lat', 'Long_']]
df_COVID19_demo['COUNTY'] = df_COVID19_demo['Admin2'] + str(',') + df_COVID19_demo['Province_State']
df_COVID19_demo.drop(columns = ['Admin2', 'Province_State'], inplace = True)
df_COVID19_demo.head()

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

         Lat      Long_           COUNTY
5  32.539527 -86.644082  Autauga,Alabama
6  30.727750 -87.722071  Baldwin,Alabama
7  31.868263 -85.387129  Barbour,Alabama
8  32.996421 -87.125115     Bibb,Alabama
9  33.982109 -86.567906   Blount,Alabama

In [18]:
start = df_COVID19.columns.get_loc('3/1/20')
end = df_COVID19.columns.get_loc('6/26/20')

df_COVID19_daily = df_COVID19.iloc[:, start: end + 1]
df_COVID19_daily.head()

,3/1/20,3/2/20,3/3/20,3/4/20,3/5/20,3/6/20,3/7/20,3/8/20,3/9/20,3/10/20,...,6/17/20,6/18/20,6/19/20,6/20/20,6/21/20,6/22/20,6/23/20,6/24/20,6/25/20,6/26/20
5,0,0,0,0,0,0,0,0,0,0,...,369,394,405,425,428,436,447,463,473,482
6,0,0,0,0,0,0,0,0,0,0,...,377,386,398,405,415,422,435,449,462,500
7,0,0,0,0,0,0,0,0,0,0,...,250,262,265,271,271,276,279,287,303,309
8,0,0,0,0,0,0,0,0,0,0,...,115,118,123,123,124,126,132,138,146,150
9,0,0,0,0,0,0,0,0,0,0,...,121,127,136,140,146,150,156,165,173,181

In [19]:
df_COVID19 = pd.concat([df_COVID19_demo, df_COVID19_daily], axis = 1)
df_COVID19.head()

,Lat,Long_,COUNTY,3/1/20,3/2/20,3/3/20,3/4/20,3/5/20,3/6/20,3/7/20,...,6/17/20,6/18/20,6/19/20,6/20/20,6/21/20,6/22/20,6/23/20,6/24/20,6/25/20,6/26/20
5,32.539527,-86.644082,"Autauga,Alabama",0,0,0,0,0,0,0,...,369,394,405,425,428,436,447,463,473,482
6,30.727750,-87.722071,"Baldwin,Alabama",0,0,0,0,0,0,0,...,377,386,398,405,415,422,435,449,462,500
7,31.868263,-85.387129,"Barbour,Alabama",0,0,0,0,0,0,0,...,250,262,265,271,271,276,279,287,303,309
8,32.996421,-87.125115,"Bibb,Alabama",0,0,0,0,0,0,0,...,115,118,123,123,124,126,132,138,146,150
9,33.982109,-86.567906,"Blount,Alabama",0,0,0,0,0,0,0,...,121,127,136,140,146,150,156,165,173,181

## Get 5 nearby county

In [438]:
df_COVID19.head()

,Lat,Long_,COUNTY,3/1/20,3/2/20,3/3/20,3/4/20,3/5/20,3/6/20,3/7/20,...,6/17/20,6/18/20,6/19/20,6/20/20,6/21/20,6/22/20,6/23/20,6/24/20,6/25/20,6/26/20
5,32.539527,-86.644082,"Autauga,Alabama",0,0,0,0,0,0,0,...,369,394,405,425,428,436,447,463,473,482
6,30.727750,-87.722071,"Baldwin,Alabama",0,0,0,0,0,0,0,...,377,386,398,405,415,422,435,449,462,500
7,31.868263,-85.387129,"Barbour,Alabama",0,0,0,0,0,0,0,...,250,262,265,271,271,276,279,287,303,309
8,32.996421,-87.125115,"Bibb,Alabama",0,0,0,0,0,0,0,...,115,118,123,123,124,126,132,138,146,150
9,33.982109,-86.567906,"Blount,Alabama",0,0,0,0,0,0,0,...,121,127,136,140,146,150,156,165,173,181

In [439]:
df_county = df_COVID19[['COUNTY', 'Lat', 'Long_']]

In [440]:
def get_NearbyCounty(df, row):
    df['Distance'] = np.sqrt((df['Lat'] - row['Lat'])**2 + (df['Long_'] - row['Long_'])**2)
    df.sort_values(by = ['Distance'], inplace = True)
    county_array = np.array(df['COUNTY'].iloc[1:6].get_values())
    return [county_array]

In [441]:
#df_sub = df_county.iloc[0:5]
#df_sub.loc[df_sub['COUNTY'] == 'Baldwin,Alabama']
df_county['NEARBY_COUNTY'] = df_county.apply(lambda x: get_NearbyCounty(df_county.copy(), x), axis = 1)
df_county.head()
#df_sub.apply(lambda x: return(x['COUNTY']), axis = 1)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,COUNTY,Lat,Long_,NEARBY_COUNTY
5,"Autauga,Alabama",32.539527,-86.644082,"[[Chilton,Alabama, Lowndes,Alabama, Elmore,Ala..."
6,"Baldwin,Alabama",30.727750,-87.722071,"[[Escambia,Florida, Mobile,Alabama, Escambia,A..."
7,"Barbour,Alabama",31.868263,-85.387129,"[[Quitman,Georgia, Henry,Alabama, Bullock,Alab..."
8,"Bibb,Alabama",32.996421,-87.125115,"[[Perry,Alabama, Chilton,Alabama, Tuscaloosa,A..."
9,"Blount,Alabama",33.982109,-86.567906,"[[Cullman,Alabama, St. Clair,Alabama, Marshall..."

In [442]:
df_county.shape

(3244, 4)

In [443]:
df_county.drop(columns = ['Lat', 'Long_'], inplace = True)
df_county.head()

/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3697: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

            COUNTY                                      NEARBY_COUNTY
5  Autauga,Alabama  [[Chilton,Alabama, Lowndes,Alabama, Elmore,Ala...
6  Baldwin,Alabama  [[Escambia,Florida, Mobile,Alabama, Escambia,A...
7  Barbour,Alabama  [[Quitman,Georgia, Henry,Alabama, Bullock,Alab...
8     Bibb,Alabama  [[Perry,Alabama, Chilton,Alabama, Tuscaloosa,A...
9   Blount,Alabama  [[Cullman,Alabama, St. Clair,Alabama, Marshall...

In [444]:
dict_NearbyCounty = df_county.set_index('COUNTY')['NEARBY_COUNTY'].to_dict()
len(dict_NearbyCounty['Autauga,Alabama'][0])

5

In [446]:
#df_sub.iloc[0]['COUNTY'] in df_sub["NEARBY_COUNTY"].iloc[3][0]

## Altering structure for COVID19 dataset

In [341]:
date_array = np.array(df_COVID19_daily.columns)

In [342]:
datetime_array = [datetime.datetime.strptime(date + '20',"%m/%d/%Y") for date in date_array]

In [346]:
datetime_list = [datetime.strftime("%m/%d/%Y") for datetime in datetime_array]

In [274]:
df_COVID19_tempo = df_COVID19.drop(columns = ['Lat', 'Long_'])
df_COVID19_tempo.set_index('COUNTY', inplace = True)

In [275]:
df_COVID19_tempo.head()

,3/1/20,3/2/20,3/3/20,3/4/20,3/5/20,3/6/20,3/7/20,3/8/20,3/9/20,3/10/20,...,6/17/20,6/18/20,6/19/20,6/20/20,6/21/20,6/22/20,6/23/20,6/24/20,6/25/20,6/26/20
COUNTY,,,,,,,,,,,,,,,,,,,,,
"Autauga,Alabama",0,0,0,0,0,0,0,0,0,0,...,369,394,405,425,428,436,447,463,473,482
"Baldwin,Alabama",0,0,0,0,0,0,0,0,0,0,...,377,386,398,405,415,422,435,449,462,500
"Barbour,Alabama",0,0,0,0,0,0,0,0,0,0,...,250,262,265,271,271,276,279,287,303,309
"Bibb,Alabama",0,0,0,0,0,0,0,0,0,0,...,115,118,123,123,124,126,132,138,146,150
"Blount,Alabama",0,0,0,0,0,0,0,0,0,0,...,121,127,136,140,146,150,156,165,173,181

In [334]:
stack_array = df_COVID19_tempo.stack().values.tolist()
len(stack_array)

382792

In [293]:
county_array = np.array([])

In [294]:
#county_array = np.append(county_array, [np.repeat(county, len(date_array)) for county in df_COVID19_tempo.index])

In [329]:
county_array = np.repeat(df_COVID19_tempo.index, len(date_array)).tolist()

In [330]:
len(county_array)

382792

In [350]:
#cum_date_array = date_array.tolist()
cum_date_array = datetime_list * len(df_COVID19_tempo.index)

In [351]:
len(cum_date_array)

382792

In [362]:
len(stack_array)

382792

In [353]:
df_COVID19_final = pd.DataFrame({'COUNTY': county_array, 'DATE': cum_date_array, 'DAILY_INCREASE': stack_array})

In [357]:
df_COVID19_final['COUNTY_AND_DATE'] = df_COVID19_final['COUNTY'] + str(',') + df_COVID19_final['DATE']

In [358]:
df_COVID19_final[(df_COVID19_final['COUNTY'] == 'Autauga,Alabama') & (df_COVID19_final['DATE'] == '06/17/2020')]

              COUNTY        DATE  DAILY_INCREASE             COUNTY_AND_DATE
108  Autauga,Alabama  06/17/2020             369  Autauga,Alabama,06/17/2020

In [392]:
df_COVID19_final.head()

            COUNTY        DATE  DAILY_INCREASE             COUNTY_AND_DATE
0  Autauga,Alabama  03/01/2020               0  Autauga,Alabama,03/01/2020
1  Autauga,Alabama  03/02/2020               0  Autauga,Alabama,03/02/2020
2  Autauga,Alabama  03/03/2020               0  Autauga,Alabama,03/03/2020
3  Autauga,Alabama  03/04/2020               0  Autauga,Alabama,03/04/2020
4  Autauga,Alabama  03/05/2020               0  Autauga,Alabama,03/05/2020

## Minor change in Social Mobility Dataset

In [375]:
df_social_mobility_merge.head()

,Social distancing index,date,% people older than 60,Population density,COVID death rate,New cases/1000 people,COUNTY
0,54,01/01/2020,19,91,0.0,0.0,"Autauga,Alabama"
1,25,01/02/2020,19,91,0.0,0.0,"Autauga,Alabama"
2,15,01/03/2020,19,91,0.0,0.0,"Autauga,Alabama"
3,33,01/04/2020,19,91,0.0,0.0,"Autauga,Alabama"
4,40,01/05/2020,19,91,0.0,0.0,"Autauga,Alabama"

In [376]:
df_social_mobility_merge[(df_social_mobility_merge['COUNTY'] == 'Autauga,Alabama') & (df_social_mobility_merge['date'] == '06/17/2020')]

,Social distancing index,date,% people older than 60,Population density,COVID death rate,New cases/1000 people,COUNTY
11058,22,06/17/2020,19,91,1.25,0.0719,"Autauga,Alabama"

In [377]:
len(df_social_mobility_merge)

559276

In [378]:
df_social_mobility_merge['date'] = [datetime.datetime.strptime(date,"%m/%d/%Y") for date in df_social_mobility_merge['date']]

In [379]:
start_date = datetime.datetime(2020, 3, 1)
end_date = datetime.datetime(2020, 6, 26)

In [387]:
df_social_mobility_part = df_social_mobility_merge[(df_social_mobility_merge['date'] >= start_date) 
                                                   & (df_social_mobility_merge['date'] <= end_date)]

In [393]:
df_social_mobility_part.head()

,Social distancing index,date,% people older than 60,Population density,COVID death rate,New cases/1000 people,COUNTY,COUNTY_AND_DATE
60,35,03/01/2020,19,91,0.0,0.0,"Autauga,Alabama","Autauga,Alabama,03/01/2020"
61,11,03/02/2020,19,91,0.0,0.0,"Autauga,Alabama","Autauga,Alabama,03/02/2020"
62,10,03/03/2020,19,91,0.0,0.0,"Autauga,Alabama","Autauga,Alabama,03/03/2020"
63,19,03/04/2020,19,91,0.0,0.0,"Autauga,Alabama","Autauga,Alabama,03/04/2020"
64,12,03/05/2020,19,91,0.0,0.0,"Autauga,Alabama","Autauga,Alabama,03/05/2020"

In [389]:
df_social_mobility_part['date'] = [datetime.strftime("%m/%d/%Y") for datetime in df_social_mobility_part['date']]

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [390]:
df_social_mobility_part.head()

,Social distancing index,date,% people older than 60,Population density,COVID death rate,New cases/1000 people,COUNTY
60,35,03/01/2020,19,91,0.0,0.0,"Autauga,Alabama"
61,11,03/02/2020,19,91,0.0,0.0,"Autauga,Alabama"
62,10,03/03/2020,19,91,0.0,0.0,"Autauga,Alabama"
63,19,03/04/2020,19,91,0.0,0.0,"Autauga,Alabama"
64,12,03/05/2020,19,91,0.0,0.0,"Autauga,Alabama"

In [394]:
df_social_mobility_part['COUNTY_AND_DATE'] = df_social_mobility_part['COUNTY'] + str(',') + df_social_mobility_part['date']
df_social_mobility_part.head()

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,Social distancing index,date,% people older than 60,Population density,COVID death rate,New cases/1000 people,COUNTY,COUNTY_AND_DATE
60,35,03/01/2020,19,91,0.0,0.0,"Autauga,Alabama","Autauga,Alabama,03/01/2020"
61,11,03/02/2020,19,91,0.0,0.0,"Autauga,Alabama","Autauga,Alabama,03/02/2020"
62,10,03/03/2020,19,91,0.0,0.0,"Autauga,Alabama","Autauga,Alabama,03/03/2020"
63,19,03/04/2020,19,91,0.0,0.0,"Autauga,Alabama","Autauga,Alabama,03/04/2020"
64,12,03/05/2020,19,91,0.0,0.0,"Autauga,Alabama","Autauga,Alabama,03/05/2020"

In [468]:
df_social_mobility_part.shape

(370756, 8)

## Combining social mobility datasets and COVID19 dataset

In [407]:
df_mobility_COVID19 = pd.merge(df_COVID19_final, df_social_mobility_part, on = ['COUNTY_AND_DATE'])

In [411]:
df_mobility_COVID19_new = df_mobility_COVID19.drop(columns = ['date', 'COUNTY_y'])

In [412]:
df_mobility_COVID19_new.head()

,COUNTY_x,DATE,DAILY_INCREASE,COUNTY_AND_DATE,Social distancing index,% people older than 60,Population density,COVID death rate,New cases/1000 people
0,"Autauga,Alabama",03/01/2020,0,"Autauga,Alabama,03/01/2020",35,19,91,0.0,0.0
1,"Autauga,Alabama",03/02/2020,0,"Autauga,Alabama,03/02/2020",11,19,91,0.0,0.0
2,"Autauga,Alabama",03/03/2020,0,"Autauga,Alabama,03/03/2020",10,19,91,0.0,0.0
3,"Autauga,Alabama",03/04/2020,0,"Autauga,Alabama,03/04/2020",19,19,91,0.0,0.0
4,"Autauga,Alabama",03/05/2020,0,"Autauga,Alabama,03/05/2020",12,19,91,0.0,0.0

In [413]:
df_mobility_COVID19_new = df_mobility_COVID19_new.rename(columns = {'COUNTY_x': 'COUNTY', 
                                                                    'DAILY_INCREASE': 'Daily increase'})

In [418]:
#df_mobility_COVID19_new[df_mobility_COVID19_new.isnull().any(axis=1)]

Empty DataFrame
Columns: [COUNTY, DATE, Daily increase, COUNTY_AND_DATE, Social distancing index, % people older than 60, Population density, COVID death rate, New cases/1000 people]
Index: []

In [419]:
df_mobility_COVID19_new = df_mobility_COVID19_new[['COUNTY_AND_DATE', 'COUNTY', 'DATE', 'Daily increase', 'Social distancing index', 
                                                   'New cases/1000 people', 'COVID death rate', '% people older than 60', 'Population density']]

In [420]:
df_mobility_COVID19_new.head()

,COUNTY_AND_DATE,COUNTY,DATE,Daily increase,Social distancing index,New cases/1000 people,COVID death rate,% people older than 60,Population density
0,"Autauga,Alabama,03/01/2020","Autauga,Alabama",03/01/2020,0,35,0.0,0.0,19,91
1,"Autauga,Alabama,03/02/2020","Autauga,Alabama",03/02/2020,0,11,0.0,0.0,19,91
2,"Autauga,Alabama,03/03/2020","Autauga,Alabama",03/03/2020,0,10,0.0,0.0,19,91
3,"Autauga,Alabama,03/04/2020","Autauga,Alabama",03/04/2020,0,19,0.0,0.0,19,91
4,"Autauga,Alabama,03/05/2020","Autauga,Alabama",03/05/2020,0,12,0.0,0.0,19,91

## Generating nearby 5 counties' average social distancing index and average daily increase in positive tests

In [479]:
df_sub = df_mobility_COVID19_new[df_mobility_COVID19_new['DATE'] == '06/15/2020']
df_sub

,COUNTY_AND_DATE,COUNTY,DATE,Daily increase,Social distancing index,New cases/1000 people,COVID death rate,% people older than 60,Population density
106,"Autauga,Alabama,06/15/2020","Autauga,Alabama",06/15/2020,364,30,0.2458,1.25,19,91
224,"Baldwin,Alabama,06/15/2020","Baldwin,Alabama",06/15/2020,368,28,0.0229,1.25,27,103
342,"Barbour,Alabama,06/15/2020","Barbour,Alabama",06/15/2020,237,29,0.2144,1.25,24,29
460,"Bibb,Alabama,06/15/2020","Bibb,Alabama",06/15/2020,108,27,0.1637,1.25,22,36
578,"Blount,Alabama,06/15/2020","Blount,Alabama",06/15/2020,114,25,0.1095,1.25,24,89
696,"Bullock,Alabama,06/15/2020","Bullock,Alabama",06/15/2020,305,35,1.5453,1.25,24,17
814,"Butler,Alabama,06/15/2020","Butler,Alabama",06/15/2020,541,29,0.7114,1.25,26,26
932,"Calhoun,Alabama,06/15/2020","Calhoun,Alabama",06/15/2020,196,32,0.0233,1.25,24,188
1050,"Chambers,Alabama,06/15/2020","Chambers,Alabama",06/15/2020,461,31,0.3372,1.25,25,56
1168,"Cherokee,Alabama,06/15/2020","Cherokee,Alabama",06/15/2020,51,24,0.0640,1.25,29,43
1286,"Chilton,Alabama,06/15/2020","Chilton,Alabama",06/15/2020,135,27,0.0981,1.25,22,63
1404,"Choctaw,Alabama,06/15/2020","Choctaw,Alabama",06/15/2020,175,31,0.2336,1.25,29,14
1522,"Clarke,Alabama,06/15/2020","Clarke,Alabama",06/15/2020,191,24,0.2230,1.25,25,19
1640,"Clay,Alabama,06/15/2020","Clay,Alabama",06/15/2020,30,31,0.0000,1.25,26,22
1758,"Cleburne,Alabama,06/15/2020","Cleburne,Alabama",06/15/2020,22,30,0.0445,1.25,26,27
1876,"Coffee,Alabama,06/15/2020","Coffee,Alabama",06/15/2020,290,27,0.1605,1.25,22,75
1994,"Colbert,Alabama,06/15/2020","Colbert,Alabama",06/15/2020,265,24,0.1461,1.25,26,87
2112,"Conecuh,Alabama,06/15/2020","Conecuh,Alabama",06/15/2020,100,28,0.6516,1.25,28,15
2230,"Coosa,Alabama,06/15/2020","Coosa,Alabama",06/15/2020,46,30,0.0933,1.25,29,16
2348,"Covington,Alabama,06/15/2020","Covington,Alabama",06/15/2020,171,20,0.5858,1.25,28,36
2466,"Crenshaw,Alabama,06/15/2020","Crenshaw,Alabama",06/15/2020,112,25,0.1688,1.25,25,23
2584,"Cullman,Alabama,06/15/2020","Cullman,Alabama",06/15/2020,273,26,0.1358,1.25,24,109
2702,"Dale,Alabama,06/15/2020","Dale,Alabama",06/15/2020,178,31,0.0953,1.25,22,88
2820,"Dallas,Alabama,06/15/2020","Dallas,Alabama",06/15/2020,503,33,0.7135,1.25,24,40
2938,"DeKalb,Alabama,06/15/2020","DeKalb,Alabama",06/15/2020,322,21,0.0887,1.25,22,91
3056,"Elmore,Alabama,06/15/2020","Elmore,Alabama",06/15/2020,547,30,0.2524,1.25,20,124
3174,"Escambia,Alabama,06/15/2020","Escambia,Alabama",06/15/2020,107,25,0.0726,1.25,24,39
3292,"Etowah,Alabama,06/15/2020","Etowah,Alabama",06/15/2020,330,28,0.1041,1.25,25,188
3410,"Fayette,Alabama,06/15/2020","Fayette,Alabama",06/15/2020,45,24,0.3854,1.25,28,26
3528,"Franklin,Alabama,06/15/2020","Franklin,Alabama",06/15/2020,730,25,0.6908,1.25,23,49
...,...,...,...,...,...,...,...,...,...
351510,"Washburn,Wisconsin,06/15/2020","Washburn,Wisconsin",06/15/2020,3,22,0.0000,1.26,34,18
351628,"Washington,Wisconsin,06/15/2020","Washington,Wisconsin",06/15/2020,294,28,0.0123,1.26,23,309
351746,"Waukesha,Wisconsin,06/15/2020","Waukesha,Wisconsin",06/15/2020,915,35,0.0256,1.26,25,687
351864,"Waupaca,Wisconsin,06/15/2020","Waupaca,Wisconsin",06/15/2020,79,21,0.0848,1.26,28,67
351982,"Waushara,Wisconsin,06/15/2020","Waushara,Wisconsin",06/15/2020,16,16,0.0000,1.26,32,38
352100,"Winnebago,Wisconsin,06/15/2020","Winnebago,Wisconsin",06/15/2020,532,31,0.0916,1.26,21,294
352218,"Wood,Wisconsin,06/15/2020","Wood,Wisconsin",06/15/2020,23,24,0.0319,1.26,26,91
352336,"Albany,Wyoming,06/15/2020","Albany,Wyoming",06/15/2020,27,24,0.0173,0.69,16,9
352454,"Big Horn,Wyoming,06/15/2020","Big Horn,Wyoming",06/15/2020,11,28,0.0281,0.69,28,4
352572,"Campbell,Wyoming,06/15/2020","Campbell,Wyoming",06/15/2020,45,18,0.0361,0.69,14,10
352690,"Carbon,Wyoming,06/15/2020","Carbon,Wyoming",06/15/2020,22,23,0.0891,0.69,22,2
352808,"Converse,Wyoming,06/15/2020","Converse,Wyoming",06/15/2020,24,23,0.0000,0.69,22,3
352926,"Crook,Wyoming,06/15/2020","Crook,Wyoming",06/15/2020,6,17,0.0447,0.69,28,3
353044,"Fremont,Wyoming,06/15/2020","Fremont,Wyoming",06/15/2020,308,24,0.0422,0.69,25,4
353162,"Goshen,Wyoming,06/15/2020","Goshen,Wyoming",06/15/2020,5,15,0.0000,0.69,29,6
353280,"Hot Springs,Wyoming,06/15/2020","Hot Springs,Wyoming",06/15/2020,12,37,0.0000,0.69,35,2
353398,"Johnson,Wyoming,06/15/2020","Johnson,Wyoming",06/15/2020,18,22,0.0000,0.69,30,2
353516,"Laramie,Wyoming,06/15/2020","Laramie,Wyoming",06/15/2020,196,23,0.0168,0.69,21,36
353634,"Lincoln,Wyoming,06/15/2020","Lincoln,Wyoming",06/15/2020,15,25,0.0000,0.69,24,5
353752,"Natrona,Wyoming,06/15/2020","Natrona,Wyoming",06/15/2020,87,23,0.0000,0.69,20,15
353870,"Niobrara,Wyoming,06/15/2020","Niobrara,Wyoming",06/15/2020,2,19,0.0000,0.69,27,1
353988,"Park,Wyoming,06/15/2020","Park,Wyoming",06/15/2020,5,24,0.0227,0.69,31,4
354106,"Platte,Wyoming,06/15/2020","Platte,Wyoming",06/15/2020,1,23,0.0000,0.69,33,4
354224,"Sheridan,Wyoming,06/15/2020","Sheridan,Wyoming",06/15/2020,19,21,0.0000,0.69,28,12
354342,"Sublette,Wyoming,06/15/2020","Sublette,Wyoming",06/15/2020,3,27,0.0000,0.69,24,2
354460,"Sweetwater,Wyoming,06/15/2020","Sweetwater,Wyoming",06/15/2020,40,24,0.0155,0.69,17,4
354578,"Teton,Wyoming,06/15/2020","Teton,Wyoming",06/15/2020,105,29,0.0144,0.69,20,5
354696,"Uinta,Wyoming,06/15/2020","Uinta,Wyoming",06/15/2020,88,28,0.4270,0.69,18,10
354814,"Washakie,Wyoming,06/15/2020","Washakie,Wyoming",06/15/2020,39,41,0.0000,0.69,28,4
354932,"Weston,Wyoming,06/15/2020","Weston,Wyoming",06/15/2020,1,23,0.0000,0.69,30,3

In [513]:
def get_NearbyAverage(df, cur_index, column_name, dictionary = dict_NearbyCounty):
    if cur_index % 2000 == 0:
        print('This is row: ', cur_index)
        
    cur_county = df['COUNTY'][df.index == cur_index].values[0]
    cur_date = df['DATE'][df.index == cur_index].values[0]
    nearby_county = dict_NearbyCounty[cur_county][0]
    
    df_subset = df[df['DATE'] == cur_date]
    #print(df_subset.head())
    
    avg = 0
    #num_county = 0
    for county in nearby_county:
        if county not in df_subset['COUNTY'].unique():
            #print(cur_county)
            avg = None
            return avg
        #print(df[column_name][(df['COUNTY'] == county) & (df['DATE'] == cur_date)].values[0])
        avg += df_subset[column_name][df_subset['COUNTY'] == county].values[0]
        #num_county += 1
    #print(num_county)
#     if num_county < 5:
#         print(cur_county)
#         print(num_county)
    avg = avg/5
    #print(avg)
    return avg

In [514]:
nearby_avg_dailyinc = [get_NearbyAverage(df_mobility_COVID19_new, index, 'Daily increase') 
              for index in df_mobility_COVID19_new.index]

This is row:  0
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
0    Autauga,Alabama,03/01/2020  Autauga,Alabama  03/01/2020               0
118  Baldwin,Alabama,03/01/2020  Baldwin,Alabama  03/01/2020               0
236  Barbour,Alabama,03/01/2020  Barbour,Alabama  03/01/2020               0
354     Bibb,Alabama,03/01/2020     Bibb,Alabama  03/01/2020               0
472   Blount,Alabama,03/01/2020   Blount,Alabama  03/01/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
0                         35                    0.0               0.0
118                       29                    0.0               0.0
236                       36                    0.0               0.0
354                       33                    0.0               0.0
472                       32                    0.0               0.0

     % people older than 60  Population density
0                        19                  91
118                      27                 103
236                      24                  29
354                      22                  36
472                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
1    Autauga,Alabama,03/02/2020  Autauga,Alabama  03/02/2020               0
119  Baldwin,Alabama,03/02/2020  Baldwin,Alabama  03/02/2020               0
237  Barbour,Alabama,03/02/2020  Barbour,Alabama  03/02/2020               0
355     Bibb,Alabama,03/02/2020     Bibb,Alabama  03/02/2020               0
473   Blount,Alabama,03/02/2020   Blount,Alabama  03/02/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
1                         11                    0.0               0.0
119                       14                    0.0               0.0
237                       17                    0.0               0.0
355                       14                    0.0               0.0
473                       17                    0.0               0.0

     % people older than 60  Population density
1                        19                  91
119                      27                 103
237                      24                  29
355                      22                  36
473                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
2    Autauga,Alabama,03/03/2020  Autauga,Alabama  03/03/2020               0
120  Baldwin,Alabama,03/03/2020  Baldwin,Alabama  03/03/2020               0
238  Barbour,Alabama,03/03/2020  Barbour,Alabama  03/03/2020               0
356     Bibb,Alabama,03/03/2020     Bibb,Alabama  03/03/2020               0
474   Blount,Alabama,03/03/2020   Blount,Alabama  03/03/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
2                         10                    0.0               0.0
120                       11                    0.0               0.0
238                        9                    0.0               0.0
356                        9                    0.0               0.0
474                        9                    0.0               0.0

     % people older than 60  Population density
2                        19                  91
120                      27                 103
238                      24                  29
356                      22                  36
474                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
3    Autauga,Alabama,03/04/2020  Autauga,Alabama  03/04/2020               0
121  Baldwin,Alabama,03/04/2020  Baldwin,Alabama  03/04/2020               0
239  Barbour,Alabama,03/04/2020  Barbour,Alabama  03/04/2020               0
357     Bibb,Alabama,03/04/2020     Bibb,Alabama  03/04/2020               0
475   Blount,Alabama,03/04/2020   Blount,Alabama  03/04/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
3                         19                    0.0               0.0
121                       18                    0.0               0.0
239                       20                    0.0               0.0
357                       18                    0.0               0.0
475                       13                    0.0               0.0

     % people older than 60  Population density
3                        19                  91
121                      27                 103
239                      24                  29
357                      22                  36
475                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
4    Autauga,Alabama,03/05/2020  Autauga,Alabama  03/05/2020               0
122  Baldwin,Alabama,03/05/2020  Baldwin,Alabama  03/05/2020               0
240  Barbour,Alabama,03/05/2020  Barbour,Alabama  03/05/2020               0
358     Bibb,Alabama,03/05/2020     Bibb,Alabama  03/05/2020               0
476   Blount,Alabama,03/05/2020   Blount,Alabama  03/05/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
4                         12                    0.0               0.0
122                       12                    0.0               0.0
240                       15                    0.0               0.0
358                        9                    0.0               0.0
476                       10                    0.0               0.0

     % people older than 60  Population density
4                        19                  91
122                      27                 103
240                      24                  29
358                      22                  36
476                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
5    Autauga,Alabama,03/06/2020  Autauga,Alabama  03/06/2020               0
123  Baldwin,Alabama,03/06/2020  Baldwin,Alabama  03/06/2020               0
241  Barbour,Alabama,03/06/2020  Barbour,Alabama  03/06/2020               0
359     Bibb,Alabama,03/06/2020     Bibb,Alabama  03/06/2020               0
477   Blount,Alabama,03/06/2020   Blount,Alabama  03/06/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
5                          9                    0.0               0.0
123                       11                    0.0               0.0
241                        9                    0.0               0.0
359                       10                    0.0               0.0
477                        9                    0.0               0.0

     % people older than 60  Population density
5                        19                  91
123                      27                 103
241                      24                  29
359                      22                  36
477                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
6    Autauga,Alabama,03/07/2020  Autauga,Alabama  03/07/2020               0
124  Baldwin,Alabama,03/07/2020  Baldwin,Alabama  03/07/2020               0
242  Barbour,Alabama,03/07/2020  Barbour,Alabama  03/07/2020               0
360     Bibb,Alabama,03/07/2020     Bibb,Alabama  03/07/2020               0
478   Blount,Alabama,03/07/2020   Blount,Alabama  03/07/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
6                         21                    0.0               0.0
124                       20                    0.0               0.0
242                       20                    0.0               0.0
360                       16                    0.0               0.0
478                       22                    0.0               0.0

     % people older than 60  Population density
6                        19                  91
124                      27                 103
242                      24                  29
360                      22                  36
478                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
7    Autauga,Alabama,03/08/2020  Autauga,Alabama  03/08/2020               0
125  Baldwin,Alabama,03/08/2020  Baldwin,Alabama  03/08/2020               0
243  Barbour,Alabama,03/08/2020  Barbour,Alabama  03/08/2020               0
361     Bibb,Alabama,03/08/2020     Bibb,Alabama  03/08/2020               0
479   Blount,Alabama,03/08/2020   Blount,Alabama  03/08/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
7                         31                    0.0               0.0
125                       32                    0.0               0.0
243                       32                    0.0               0.0
361                       32                    0.0               0.0
479                       34                    0.0               0.0

     % people older than 60  Population density
7                        19                  91
125                      27                 103
243                      24                  29
361                      22                  36
479                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
8    Autauga,Alabama,03/09/2020  Autauga,Alabama  03/09/2020               0
126  Baldwin,Alabama,03/09/2020  Baldwin,Alabama  03/09/2020               0
244  Barbour,Alabama,03/09/2020  Barbour,Alabama  03/09/2020               0
362     Bibb,Alabama,03/09/2020     Bibb,Alabama  03/09/2020               0
480   Blount,Alabama,03/09/2020   Blount,Alabama  03/09/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
8                         12                    0.0               0.0
126                       15                    0.0               0.0
244                       11                    0.0               0.0
362                        7                    0.0               0.0
480                       10                    0.0               0.0

     % people older than 60  Population density
8                        19                  91
126                      27                 103
244                      24                  29
362                      22                  36
480                      24                  89

                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
9    Autauga,Alabama,03/10/2020  Autauga,Alabama  03/10/2020               0
127  Baldwin,Alabama,03/10/2020  Baldwin,Alabama  03/10/2020               0
245  Barbour,Alabama,03/10/2020  Barbour,Alabama  03/10/2020               0
363     Bibb,Alabama,03/10/2020     Bibb,Alabama  03/10/2020               0
481   Blount,Alabama,03/10/2020   Blount,Alabama  03/10/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
9                         17                    0.0               0.0
127                       14                    0.0               0.0
245                       12                    0.0               0.0
363                       13                    0.0               0.0
481                       11                    0.0               0.0

     % people older than 60  Population density
9                        19                  91
127                      27                 103
245                      24                  29
363                      22                  36
481                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
10   Autauga,Alabama,03/11/2020  Autauga,Alabama  03/11/2020               0
128  Baldwin,Alabama,03/11/2020  Baldwin,Alabama  03/11/2020               0
246  Barbour,Alabama,03/11/2020  Barbour,Alabama  03/11/2020               0
364     Bibb,Alabama,03/11/2020     Bibb,Alabama  03/11/2020               0
482   Blount,Alabama,03/11/2020   Blount,Alabama  03/11/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
10                         8                    0.0               0.0
128                       12                    0.0               0.0
246                        8                    0.0               0.0
364                        8                    0.0               0.0
482                       10                    0.0               0.0

     % people older than 60  Population density
10                       19                  91
128                      27                 103
246                      24                  29
364                      22                  36
482                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
11   Autauga,Alabama,03/12/2020  Autauga,Alabama  03/12/2020               0
129  Baldwin,Alabama,03/12/2020  Baldwin,Alabama  03/12/2020               0
247  Barbour,Alabama,03/12/2020  Barbour,Alabama  03/12/2020               0
365     Bibb,Alabama,03/12/2020     Bibb,Alabama  03/12/2020               0
483   Blount,Alabama,03/12/2020   Blount,Alabama  03/12/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
11                        10                    0.0               0.0
129                       12                    0.0               0.0
247                       10                    0.0               0.0
365                        9                    0.0               0.0
483                        8                    0.0               0.0

     % people older than 60  Population density
11                       19                  91
129                      27                 103
247                      24                  29
365                      22                  36
483                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
12   Autauga,Alabama,03/13/2020  Autauga,Alabama  03/13/2020               0
130  Baldwin,Alabama,03/13/2020  Baldwin,Alabama  03/13/2020               0
248  Barbour,Alabama,03/13/2020  Barbour,Alabama  03/13/2020               0
366     Bibb,Alabama,03/13/2020     Bibb,Alabama  03/13/2020               0
484   Blount,Alabama,03/13/2020   Blount,Alabama  03/13/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
12                        10                    0.0               0.0
130                       12                    0.0               0.0
248                        8                    0.0               0.0
366                        7                    0.0               0.0
484                        8                    0.0               0.0

     % people older than 60  Population density
12                       19                  91
130                      27                 103
248                      24                  29
366                      22                  36
484                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
13   Autauga,Alabama,03/14/2020  Autauga,Alabama  03/14/2020               0
131  Baldwin,Alabama,03/14/2020  Baldwin,Alabama  03/14/2020               0
249  Barbour,Alabama,03/14/2020  Barbour,Alabama  03/14/2020               0
367     Bibb,Alabama,03/14/2020     Bibb,Alabama  03/14/2020               0
485   Blount,Alabama,03/14/2020   Blount,Alabama  03/14/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
13                        23                    0.0               0.0
131                       23                    0.0               0.0
249                       16                    0.0               0.0
367                       20                    0.0               0.0
485                       23                    0.0               0.0

     % people older than 60  Population density
13                       19                  91
131                      27                 103
249                      24                  29
367                      22                  36
485                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
14   Autauga,Alabama,03/15/2020  Autauga,Alabama  03/15/2020               0
132  Baldwin,Alabama,03/15/2020  Baldwin,Alabama  03/15/2020               1
250  Barbour,Alabama,03/15/2020  Barbour,Alabama  03/15/2020               0
368     Bibb,Alabama,03/15/2020     Bibb,Alabama  03/15/2020               0
486   Blount,Alabama,03/15/2020   Blount,Alabama  03/15/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
14                        42                 0.0000               0.0
132                       34                 0.0015               0.0
250                       29                 0.0000               0.0
368                       35                 0.0000               0.0
486                       47                 0.0000               0.0

     % people older than 60  Population density
14                       19                  91
132                      27                 103
250                      24                  29
368                      22                  36
486                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
15   Autauga,Alabama,03/16/2020  Autauga,Alabama  03/16/2020               0
133  Baldwin,Alabama,03/16/2020  Baldwin,Alabama  03/16/2020               1
251  Barbour,Alabama,03/16/2020  Barbour,Alabama  03/16/2020               0
369     Bibb,Alabama,03/16/2020     Bibb,Alabama  03/16/2020               0
487   Blount,Alabama,03/16/2020   Blount,Alabama  03/16/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
15                        19                 0.0000               0.0
133                       17                 0.0015               0.0
251                       10                 0.0000               0.0
369                       14                 0.0000               0.0
487                       18                 0.0000               0.0

     % people older than 60  Population density
15                       19                  91
133                      27                 103
251                      24                  29
369                      22                  36
487                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
16   Autauga,Alabama,03/17/2020  Autauga,Alabama  03/17/2020               0
134  Baldwin,Alabama,03/17/2020  Baldwin,Alabama  03/17/2020               1
252  Barbour,Alabama,03/17/2020  Barbour,Alabama  03/17/2020               0
370     Bibb,Alabama,03/17/2020     Bibb,Alabama  03/17/2020               0
488   Blount,Alabama,03/17/2020   Blount,Alabama  03/17/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
16                        21                 0.0000               0.0
134                       22                 0.0015               0.0
252                       14                 0.0000               0.0
370                       16                 0.0000               0.0
488                       21                 0.0000               0.0

     % people older than 60  Population density
16                       19                  91
134                      27                 103
252                      24                  29
370                      22                  36
488                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
17   Autauga,Alabama,03/18/2020  Autauga,Alabama  03/18/2020               0
135  Baldwin,Alabama,03/18/2020  Baldwin,Alabama  03/18/2020               1
253  Barbour,Alabama,03/18/2020  Barbour,Alabama  03/18/2020               0
371     Bibb,Alabama,03/18/2020     Bibb,Alabama  03/18/2020               0
489   Blount,Alabama,03/18/2020   Blount,Alabama  03/18/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
17                        23                    0.0               0.0
135                       24                    0.0               0.0
253                       12                    0.0               0.0
371                       20                    0.0               0.0
489                       27                    0.0               0.0

     % people older than 60  Population density
17                       19                  91
135                      27                 103
253                      24                  29
371                      22                  36
489                      24                  89

                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
18   Autauga,Alabama,03/19/2020  Autauga,Alabama  03/19/2020               0
136  Baldwin,Alabama,03/19/2020  Baldwin,Alabama  03/19/2020               1
254  Barbour,Alabama,03/19/2020  Barbour,Alabama  03/19/2020               0
372     Bibb,Alabama,03/19/2020     Bibb,Alabama  03/19/2020               0
490   Blount,Alabama,03/19/2020   Blount,Alabama  03/19/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
18                        27                    0.0               0.0
136                       26                    0.0               0.0
254                       14                    0.0               0.0
372                       25                    0.0               0.0
490                       25                    0.0               0.0

     % people older than 60  Population density
18                       19                  91
136                      27                 103
254                      24                  29
372                      22                  36
490                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
19   Autauga,Alabama,03/20/2020  Autauga,Alabama  03/20/2020               0
137  Baldwin,Alabama,03/20/2020  Baldwin,Alabama  03/20/2020               2
255  Barbour,Alabama,03/20/2020  Barbour,Alabama  03/20/2020               0
373     Bibb,Alabama,03/20/2020     Bibb,Alabama  03/20/2020               0
491   Blount,Alabama,03/20/2020   Blount,Alabama  03/20/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
19                        26                 0.0000               0.0
137                       27                 0.0015               0.0
255                       12                 0.0000               0.0
373                       23                 0.0000               0.0
491                       25                 0.0000               0.0

     % people older than 60  Population density
19                       19                  91
137                      27                 103
255                      24                  29
373                      22                  36
491                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
20   Autauga,Alabama,03/21/2020  Autauga,Alabama  03/21/2020               0
138  Baldwin,Alabama,03/21/2020  Baldwin,Alabama  03/21/2020               2
256  Barbour,Alabama,03/21/2020  Barbour,Alabama  03/21/2020               0
374     Bibb,Alabama,03/21/2020     Bibb,Alabama  03/21/2020               0
492   Blount,Alabama,03/21/2020   Blount,Alabama  03/21/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
20                        44                 0.0000               0.0
138                       49                 0.0015               0.0
256                       26                 0.0000               0.0
374                       36                 0.0000               0.0
492                       46                 0.0000               0.0

     % people older than 60  Population density
20                       19                  91
138                      27                 103
256                      24                  29
374                      22                  36
492                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
21   Autauga,Alabama,03/22/2020  Autauga,Alabama  03/22/2020               0
139  Baldwin,Alabama,03/22/2020  Baldwin,Alabama  03/22/2020               2
257  Barbour,Alabama,03/22/2020  Barbour,Alabama  03/22/2020               0
375     Bibb,Alabama,03/22/2020     Bibb,Alabama  03/22/2020               0
493   Blount,Alabama,03/22/2020   Blount,Alabama  03/22/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
21                        64                 0.0000               0.0
139                       59                 0.0015               0.0
257                       42                 0.0000               0.0
375                       54                 0.0000               0.0
493                       58                 0.0000               0.0

     % people older than 60  Population density
21                       19                  91
139                      27                 103
257                      24                  29
375                      22                  36
493                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
22   Autauga,Alabama,03/23/2020  Autauga,Alabama  03/23/2020               0
140  Baldwin,Alabama,03/23/2020  Baldwin,Alabama  03/23/2020               3
258  Barbour,Alabama,03/23/2020  Barbour,Alabama  03/23/2020               0
376     Bibb,Alabama,03/23/2020     Bibb,Alabama  03/23/2020               0
494   Blount,Alabama,03/23/2020   Blount,Alabama  03/23/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
22                        34                 0.0000               0.0
140                       38                 0.0015               0.0
258                       25                 0.0000               0.0
376                       35                 0.0000               0.0
494                       39                 0.0000               0.0

     % people older than 60  Population density
22                       19                  91
140                      27                 103
258                      24                  29
376                      22                  36
494                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
23   Autauga,Alabama,03/24/2020  Autauga,Alabama  03/24/2020               1
141  Baldwin,Alabama,03/24/2020  Baldwin,Alabama  03/24/2020               4
259  Barbour,Alabama,03/24/2020  Barbour,Alabama  03/24/2020               0
377     Bibb,Alabama,03/24/2020     Bibb,Alabama  03/24/2020               0
495   Blount,Alabama,03/24/2020   Blount,Alabama  03/24/2020               0

     Social distancing index  New cases/1000 people  COVID death rate  \
23                        36                 0.0060               0.0
141                       40                 0.0031               0.0
259                       19                 0.0000               0.0
377                       31                 0.0000               0.0
495                       36                 0.0000               0.0

     % people older than 60  Population density
23                       19                  91
141                      27                 103
259                      24                  29
377                      22                  36
495                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
24   Autauga,Alabama,03/25/2020  Autauga,Alabama  03/25/2020               4
142  Baldwin,Alabama,03/25/2020  Baldwin,Alabama  03/25/2020               4
260  Barbour,Alabama,03/25/2020  Barbour,Alabama  03/25/2020               0
378     Bibb,Alabama,03/25/2020     Bibb,Alabama  03/25/2020               0
496   Blount,Alabama,03/25/2020   Blount,Alabama  03/25/2020               1

     Social distancing index  New cases/1000 people  COVID death rate  \
24                        33                 0.0240              0.07
142                       40                 0.0031              0.07
260                       18                 0.0000              0.07
378                       24                 0.0000              0.07
496                       32                 0.0058              0.07

     % people older than 60  Population density
24                       19                  91
142                      27                 103
260                      24                  29
378                      22                  36
496                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
25   Autauga,Alabama,03/26/2020  Autauga,Alabama  03/26/2020               6
143  Baldwin,Alabama,03/26/2020  Baldwin,Alabama  03/26/2020               5
261  Barbour,Alabama,03/26/2020  Barbour,Alabama  03/26/2020               0
379     Bibb,Alabama,03/26/2020     Bibb,Alabama  03/26/2020               0
497   Blount,Alabama,03/26/2020   Blount,Alabama  03/26/2020               2

     Social distancing index  New cases/1000 people  COVID death rate  \
25                        28                 0.0360              0.06
143                       37                 0.0031              0.06
261                       15                 0.0000              0.06
379                       27                 0.0000              0.06
497                       32                 0.0115              0.06

     % people older than 60  Population density
25                       19                  91
143                      27                 103
261                      24                  29
379                      22                  36
497                      24                  89

                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
26   Autauga,Alabama,03/27/2020  Autauga,Alabama  03/27/2020               6
144  Baldwin,Alabama,03/27/2020  Baldwin,Alabama  03/27/2020               5
262  Barbour,Alabama,03/27/2020  Barbour,Alabama  03/27/2020               0
380     Bibb,Alabama,03/27/2020     Bibb,Alabama  03/27/2020               0
498   Blount,Alabama,03/27/2020   Blount,Alabama  03/27/2020               4

     Social distancing index  New cases/1000 people  COVID death rate  \
26                        30                 0.0300              0.21
144                       36                 0.0015              0.21
262                       16                 0.0000              0.21
380                       22                 0.0000              0.21
498                       25                 0.0231              0.21

     % people older than 60  Population density
26                       19                  91
144                      27                 103
262                      24                  29
380                      22                  36
498                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
27   Autauga,Alabama,03/28/2020  Autauga,Alabama  03/28/2020               6
145  Baldwin,Alabama,03/28/2020  Baldwin,Alabama  03/28/2020              10
263  Barbour,Alabama,03/28/2020  Barbour,Alabama  03/28/2020               0
381     Bibb,Alabama,03/28/2020     Bibb,Alabama  03/28/2020               0
499   Blount,Alabama,03/28/2020   Blount,Alabama  03/28/2020               5

     Social distancing index  New cases/1000 people  COVID death rate  \
27                        39                 0.0120              0.19
145                       51                 0.0092              0.19
263                       26                 0.0000              0.19
381                       40                 0.0000              0.19
499                       43                 0.0231              0.19

     % people older than 60  Population density
27                       19                  91
145                      27                 103
263                      24                  29
381                      22                  36
499                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
28   Autauga,Alabama,03/29/2020  Autauga,Alabama  03/29/2020               6
146  Baldwin,Alabama,03/29/2020  Baldwin,Alabama  03/29/2020              15
264  Barbour,Alabama,03/29/2020  Barbour,Alabama  03/29/2020               0
382     Bibb,Alabama,03/29/2020     Bibb,Alabama  03/29/2020               0
500   Blount,Alabama,03/29/2020   Blount,Alabama  03/29/2020               5

     Social distancing index  New cases/1000 people  COVID death rate  \
28                        58                 0.0000              0.39
146                       64                 0.0153              0.39
264                       44                 0.0000              0.39
382                       51                 0.0000              0.39
500                       57                 0.0173              0.39

     % people older than 60  Population density
28                       19                  91
146                      27                 103
264                      24                  29
382                      22                  36
500                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
29   Autauga,Alabama,03/30/2020  Autauga,Alabama  03/30/2020               6
147  Baldwin,Alabama,03/30/2020  Baldwin,Alabama  03/30/2020              18
265  Barbour,Alabama,03/30/2020  Barbour,Alabama  03/30/2020               0
383     Bibb,Alabama,03/30/2020     Bibb,Alabama  03/30/2020               2
501   Blount,Alabama,03/30/2020   Blount,Alabama  03/30/2020               5

     Social distancing index  New cases/1000 people  COVID death rate  \
29                        37                 0.0000              0.36
147                       45                 0.0199              0.36
265                       24                 0.0000              0.36
383                       27                 0.0298              0.36
501                       33                 0.0058              0.36

     % people older than 60  Population density
29                       19                  91
147                      27                 103
265                      24                  29
383                      22                  36
501                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
30   Autauga,Alabama,03/31/2020  Autauga,Alabama  03/31/2020               7
148  Baldwin,Alabama,03/31/2020  Baldwin,Alabama  03/31/2020              19
266  Barbour,Alabama,03/31/2020  Barbour,Alabama  03/31/2020               0
384     Bibb,Alabama,03/31/2020     Bibb,Alabama  03/31/2020               3
502   Blount,Alabama,03/31/2020   Blount,Alabama  03/31/2020               5

     Social distancing index  New cases/1000 people  COVID death rate  \
30                        44                 0.0060              0.76
148                       48                 0.0138              0.76
266                       28                 0.0000              0.76
384                       36                 0.0446              0.76
502                       39                 0.0000              0.76

     % people older than 60  Population density
30                       19                  91
148                      27                 103
266                      24                  29
384                      22                  36
502                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
31   Autauga,Alabama,04/01/2020  Autauga,Alabama  04/01/2020               8
149  Baldwin,Alabama,04/01/2020  Baldwin,Alabama  04/01/2020              20
267  Barbour,Alabama,04/01/2020  Barbour,Alabama  04/01/2020               0
385     Bibb,Alabama,04/01/2020     Bibb,Alabama  04/01/2020               3
503   Blount,Alabama,04/01/2020   Blount,Alabama  04/01/2020               5

     Social distancing index  New cases/1000 people  COVID death rate  \
31                        31                 0.0120              0.89
149                       41                 0.0076              0.89
267                       22                 0.0000              0.89
385                       27                 0.0446              0.89
503                       26                 0.0000              0.89

     % people older than 60  Population density
31                       19                  91
149                      27                 103
267                      24                  29
385                      22                  36
503                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
32   Autauga,Alabama,04/02/2020  Autauga,Alabama  04/02/2020              10
150  Baldwin,Alabama,04/02/2020  Baldwin,Alabama  04/02/2020              24
268  Barbour,Alabama,04/02/2020  Barbour,Alabama  04/02/2020               0
386     Bibb,Alabama,04/02/2020     Bibb,Alabama  04/02/2020               4
504   Blount,Alabama,04/02/2020   Blount,Alabama  04/02/2020               6

     Social distancing index  New cases/1000 people  COVID death rate  \
32                        31                 0.0240              0.98
150                       43                 0.0092              0.98
268                       20                 0.0000              0.98
386                       24                 0.0298              0.98
504                       30                 0.0058              0.98

     % people older than 60  Population density
32                       19                  91
150                      27                 103
268                      24                  29
386                      22                  36
504                      24                  89

                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
33   Autauga,Alabama,04/03/2020  Autauga,Alabama  04/03/2020              12
151  Baldwin,Alabama,04/03/2020  Baldwin,Alabama  04/03/2020              28
269  Barbour,Alabama,04/03/2020  Barbour,Alabama  04/03/2020               1
387     Bibb,Alabama,04/03/2020     Bibb,Alabama  04/03/2020               4
505   Blount,Alabama,04/03/2020   Blount,Alabama  04/03/2020               9

     Social distancing index  New cases/1000 people  COVID death rate  \
33                        26                 0.0300              1.01
151                       41                 0.0138              1.01
269                       11                 0.0134              1.01
387                       21                 0.0149              1.01
505                       19                 0.0231              1.01

     % people older than 60  Population density
33                       19                  91
151                      27                 103
269                      24                  29
387                      22                  36
505                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
34   Autauga,Alabama,04/04/2020  Autauga,Alabama  04/04/2020              12
152  Baldwin,Alabama,04/04/2020  Baldwin,Alabama  04/04/2020              29
270  Barbour,Alabama,04/04/2020  Barbour,Alabama  04/04/2020               2
388     Bibb,Alabama,04/04/2020     Bibb,Alabama  04/04/2020               4
506   Blount,Alabama,04/04/2020   Blount,Alabama  04/04/2020              10

     Social distancing index  New cases/1000 people  COVID death rate  \
34                        48                 0.0240               1.1
152                       57                 0.0138               1.1
270                       31                 0.0268               1.1
388                       45                 0.0149               1.1
506                       43                 0.0288               1.1

     % people older than 60  Population density
34                       19                  91
152                      27                 103
270                      24                  29
388                      22                  36
506                      24                  89
                COUNTY_AND_DATE           COUNTY        DATE  Daily increase  \
35   Autauga,Alabama,04/05/2020  Autauga,Alabama  04/05/2020              12
153  Baldwin,Alabama,04/05/2020  Baldwin,Alabama  04/05/2020              29
271  Barbour,Alabama,04/05/2020  Barbour,Alabama  04/05/2020               2
389     Bibb,Alabama,04/05/2020     Bibb,Alabama  04/05/2020               5
507   Blount,Alabama,04/05/2020   Blount,Alabama  04/05/2020              10

     Social distancing index  New cases/1000 people  COVID death rate  \
35                        69                 0.0120              1.02
153                       71                 0.0076              1.02
271                       51                 0.0268              1.02
389                       58                 0.0149              1.02
507                       64                 0.0231              1.02

     % people older than 60  Population density
35                       19                  91
153                      27                 103
271                      24                  29
389                      22                  36
507                      24                  89

KeyboardInterrupt:

In [463]:
key = df_sub['COUNTY'][df_sub.index == 120].values[0]
print(key)
date = df_sub['DATE'][df_sub.index == 120].values[0]
print(date)
dict_NearbyCounty[key][0]

Baldwin,Alabama
03/03/2020

array(['Escambia,Florida', 'Mobile,Alabama', 'Escambia,Alabama',
       'Santa Rosa,Florida', 'Washington,Alabama'], dtype=object)

In [471]:
df_sub.index

Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            990, 991, 992, 993, 994, 995, 996, 997, 998, 999],
           dtype='int64', length=1000)

In [ ]:
print(len(df_hospital_group))
print(len(df_social_mobility_current))
print(len(df_COVID19))

In [ ]:
df_basic = pd.merge(df_COVID19, pd.merge(df_hospital_group, df_social_mobility_current, on = ['COUNTY']), on = ['COUNTY'])
#print(len(df_basic))
print(df_basic.iloc[0])
df_clean = df_basic.drop(columns = ['Admin2', 'Province_State', 'CTNAME', 'STFIPS', 'date', 'state_name', 'fips'])
state_col = df_clean.pop('COUNTY')
df_clean.insert(0, 'COUNTY', state_col)
df_clean.to_csv('./social_mobility_and _covid19.csv')
print(df_clean.shape)
df_clean.head()

In [ ]:
county_list = df_hospital["COUNTY_NAME"].unique()
np.any([type(i) == float for i in county_list])
check = [type(i) == float for i in county_list]
for i in range(len(check)):
    if check[i] == True:
        print(i)
        print(county_list[i])
print(county_list[1410:1420])
#len(county_list)

In [ ]:
df_social_mobility = pd.read_csv('/Users/jessie/Desktop/summer_project/social_mobility_data(up_to_date)/County.csv')

In [ ]:
df_social_mobility.head()

In [ ]:
df_social_mobility.iloc[0]

In [ ]:
df_social_mobility.isnull().sum()

In [ ]:
len(df_social_mobility['CTNAME'].unique())
type(df_social_mobility['CTNAME'].unique())
print(df_social_mobility['CTNAME'].unique())

In [ ]:
np.intersect1d(df_hospital['COUNTY_NAME'].unique(), df_social_mobility['CTNAME'].unique())

In [ ]:
pwd

In [ ]:
cd Desktop/summer_project/

In [ ]:
cd '/Users/jessie/Documents/GitHub/'

In [ ]:
ls

In [ ]:
cd COVID-19

In [ ]:
ls

In [ ]:
cd csse_covid_19_data/

In [ ]:
ls

In [ ]:
cd  csse_covid_19_time_series

In [ ]:
ls